server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

jwt:
  secret: DAKjfg1ndlmkngl6jeEOlgkdslmsd;gl78LGlcdkni27NKmksdhfPcdlgfr7vdkhgrpOgmflbfY